import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.concurrent.ThreadLocalRandom;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        Quote swansonism = getWebQuote();
        if (swansonism == null) {
            Quote[] quotes = quoteArr();
            int random = ThreadLocalRandom.current().nextInt(quotes.length);
            System.out.println(quotes[random]);
        } else {
            System.out.println(swansonism);
        }
;

    }

    public static Quote[] quoteArr() {
        try {
            byte[] text = Files.readAllBytes(Paths.get("assets/recentquotes.json"));
            Gson gson = new Gson();
            Quote[] quotes = gson.fromJson(new String(text), Quote[].class);
            return quotes;

        }
        catch (IOException e) {
            System.err.println(e);
            return null;
        }
    }

    public static Quote getWebQuote() {
        try {
            URL url = new URL("https://ron-swanson-quotes.herokuapp.com/v2/quotes");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("GET");

            //Used from the example found at https://www.baeldung.com/java-http-request
            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer content = new StringBuffer();
            while ((inputLine = in.readLine()) != null) {
                content.append(inputLine);
            }
            Quote quote = new Quote("Ron Swanson", content.deleteCharAt(0).deleteCharAt(content.length() -1 ).toString());
            saveQuote(quote);
            in.close();
            return quote;
        }
        catch (IOException e) {
            System.out.println("Couldn't connect to the internet, getting a local quote instead");
        }
        return null;
    }

    public static void saveQuote(Quote toSave) {
        Gson gson = new Gson();
        try {
            System.out.println("Saving the quote");
            FileWriter jsonQuotes = new FileWriter("assets/swansonquotes.json", true);
            jsonQuotes.write("," + gson.toJson(toSave) + "\n]");
            jsonQuotes.close();
        } catch (IOException e) {
            System.out.println("Something went wrong while trying to save the quote");
            System.err.println(e);
        }
    }
}
